server:
  port: 3000
  base-url: /siper
db:
  description: base de prueba
  host: localhost
  port: 5432
  database: siper_db
  schema: siper
  user: siper_admin
  password: cambiar_esta_clave
install:
  dump:
    drop-his: false
    db:
      owner: siper_owner
client-setup: 
  lang: es
devel:
  delay: 0
log:
  db:
    on-demand: true